### ISSUE TITLE
Tweets without the image when using sendTweet

### ISSUE THREAD

**Issue by Shrey00** [elizaOS/agent-twitter-client#12]
Saw there is update in the code and sendTweetWithMedia is removed and image can be sent using sendTweet, I tried but it posted without the image.
here's the part of code - 
```   const img = await fetch(imgUrl);
      const arrayBuffer = await img.arrayBuffer();
      const imgBuffer = Buffer.from(arrayBuffer);
      const response = await scraper.sendTweet(replyText, tweetId, {data:imgBuffer,mediaType: 'image/jpeg'} );
```
It works with sendTweetWithMedia(), just putting the imgBuffer in array, as it needs Buffer[]

**Comment by denizekiz** [comment]
I realised I wasnt use latest version, in eliza repo. Update package to latest 0.0.16 not 0.0.14

**Comment by denizekiz** [comment]
This issue can be closed. 

> > I realised I wasnt use latest version, in eliza repo. Update package to latest 0.0.16 not 0.0.14
> > Okay, thanks.
